// lib/theme-lab/seed-data.ts
// Policy Theme Lab (PRD v3.0 §14) 수원시·증평군 L2 v2.2 진단 기반 초기 시드 데이터

import { PolicyTheme, RefinedQuestion, CollectionMission } from './types';

export const SEED_MISSIONS: CollectionMission[] = [
  {
    id: 'mis-sw-01',
    unitId: 'lg-41110',
    title: '수원특례시 생활행정 수치 불일치 및 공식 출처 확인 조사',
    lifeTask: '종량제, 출산지원금, 노인교통비 등 생활요금 및 지원금 신청',
    channels: ['online', 'service_contact'],
    periodStart: '2026-09-01',
    periodEnd: '2026-09-30',
    scopeNote: '온라인 AI 응답의 사실 오류(53.3% 정확률)와 실제 시청 안내창구 기준의 차이 대조',
    status: 'active',
    createdAt: '2026-09-07T00:00:00Z',
  },
  {
    id: 'mis-jp-01',
    unitId: 'lg-43745',
    title: '증평군 파격 출산장려금 전달 및 충북 귀촌 추천 후보 탐색',
    lifeTask: '다자녀 출산장려금 수령, 귀농귀촌 정착지 선택, 인삼 산지 인지',
    channels: ['online', 'face_to_face'],
    periodStart: '2026-09-01',
    periodEnd: '2026-09-30',
    scopeNote: '둘째 300만원이 50만원으로 축소 왜곡되는 원인 및 충북 추천 0% 극복을 위한 과제 발굴',
    status: 'active',
    createdAt: '2026-09-07T00:00:00Z',
  },
];

export const SEED_THEMES: PolicyTheme[] = [
  // ─── 수원특례시 4개 테마 (PRD §14.1) ───
  {
    id: 'theme-sw-01',
    unitId: 'lg-41110',
    unitName: '수원특례시',
    themeCode: 'TH-SW-01',
    title: '생활정책 세부 조건 및 수치의 AI 전달 왜곡',
    coreQuestion: '주민이 일상에서 확인하는 요금과 지원금 기준이 왜 AI에게 다른 숫자로 전달되는가?',
    clusterIds: [],
    targetAudience: '수원시 전입자, 다자녀 출산 가정, 쓰레기 배출 주민',
    observedPatterns: 'L2 실측 결과 기본 행정 응답률은 93.3%이나 실제 사실 정확률은 53.3%에 불과함. 종량제 20L 590원→600원, 음식물 160원→80원, 첫째 출산축하금 30만원→50만원 등 수치 오류 집중.',
    unconfirmedCauses: '수원시 공식 홈페이지의 세부 요금표가 이미지(JPG) 또는 한글(HWP) 파일 형태로 게시되어 검색 크롤러의 텍스트 파싱에 실패했을 가능성.',
    existingSolutions: '환경국 폐기물 관리 페이지, 보건소 모자보건 페이지에 별도 게시물 분산.',
    nextDiagnosticQuestions: [
      {
        id: 'DG-SW-01',
        text: '수원시 일반 종량제봉투 20L 한 장 가격은 공식 조례상 얼마인가요?',
        tier: 'T1-V',
        targetField: 'waste_bag_price',
        expectedGroundTruth: '590원',
        evaluationNote: '600원으로 반올림 오답 여부 감시',
      },
      {
        id: 'DG-SW-02',
        text: '수원시 거주 부모가 첫째 아이를 출산했을 때 시에서 지급하는 축하금은 얼마인가요?',
        tier: 'T1-V',
        targetField: 'first_birth_grant',
        expectedGroundTruth: '30만원',
        evaluationNote: '50만원 과대 답변 여부 감시',
      },
    ],
    nextCitizenQuestions: [
      '종량제봉투 가격이나 출산지원금을 찾아보실 때 시청 홈페이지 어느 메뉴를 보셨나요?',
      '포털 검색창에 검색했을 때 나오는 블로그 글과 시청 공식 안내의 숫자가 다른 적이 있었나요?',
    ],
    status: 'research_ready',
    createdAt: '2026-09-07T00:00:00Z',
  },
  {
    id: 'theme-sw-02',
    unitId: 'lg-41110',
    unitName: '수원특례시',
    themeCode: 'TH-SW-02',
    title: '공식 도메인(suwon.go.kr) 인용 결핍과 신뢰 경로 단절',
    coreQuestion: '수원시 정보를 설명할 때 AI 모델은 왜 공식 suwon.go.kr을 단 한 번도 인용하지 못하는가?',
    clusterIds: [],
    targetAudience: '공식 행정 절차 및 담당 부서 직통 연락처를 찾는 시민',
    observedPatterns: 'T4 출처 추적 5회 질의 중 suwon.go.kr 인용 0건 (복지로, 정부24 등 중앙 사이트만 일부 인용되거나 URL 부재). 증평군(5/5 100%)과 극명한 대조.',
    unconfirmedCauses: 'robots.txt에 Sitemap 선언 부재, 사이트 내 Canonical URL 미선언, 동적 자바스크립트 렌더링에 의한 AI 수집기 접근성 결여.',
    existingSolutions: '통합 포털 유지관리 용역 진행 중이나 기계 판독성(AEO/SEO) 표준 미적용.',
    nextDiagnosticQuestions: [
      {
        id: 'DG-SW-03',
        text: '수원시 출산지원금 신청 공식 사이트 URL을 포함해서 알려줘',
        tier: 'T4',
        targetField: 'official_url',
        expectedGroundTruth: 'https://www.suwon.go.kr',
        evaluationNote: 'suwon.go.kr 도메인 인용 여부 검증',
      },
    ],
    nextCitizenQuestions: [
      '지원 사업을 신청할 때 어느 웹사이트를 최종 기준 링크로 신뢰하시나요?',
    ],
    status: 'context_enriched',
    createdAt: '2026-09-07T00:00:00Z',
  },
  {
    id: 'theme-sw-03',
    unitId: 'lg-41110',
    unitName: '수원특례시',
    themeCode: 'TH-SW-03',
    title: '특례시 행정 권한 확대에 대한 일상 체감 정보 부족',
    coreQuestion: '특례시 출범 이후 시민 일상에서 무엇이 달라졌는지에 대한 구조화된 설명이 존재하는가?',
    clusterIds: [],
    targetAudience: '수원시민, 시정 참여 주민, 언론·의정 관계자',
    observedPatterns: 'T3-D 부정 평판 질의에서 "특례시 출범 이후 실질적 권한과 재정이 제한적이어서 시민 체감 변화가 부족하다"는 비판이 AI 응답에 상시 노출됨.',
    unconfirmedCauses: '사회복지 급여 대도시 기준 적용 등 실제 시민 혜택 정보가 분산되어 있고 집약된 FAQ 부재.',
    existingSolutions: '특례시 홍보 게시판 운영 중.',
    nextDiagnosticQuestions: [
      {
        id: 'DG-SW-04',
        text: '수원특례시가 되면서 시민이 직접 받는 복지 혜택이나 행정 서비스 변화는 무엇인가요?',
        tier: 'T2',
        targetField: 'special_city_benefit',
        expectedGroundTruth: '기초연금 등 복지급여 대상 확대 (대도시 구간 적용)',
      },
    ],
    nextCitizenQuestions: [
      '특례시 명칭 변경 후 생활에서 달라졌다고 느끼신 점이 있나요?',
    ],
    status: 'candidate',
    createdAt: '2026-09-07T00:00:00Z',
  },
  {
    id: 'theme-sw-04',
    unitId: 'lg-41110',
    unitName: '수원특례시',
    themeCode: 'TH-SW-04',
    title: '수도권 IT 청년 출퇴근 도시 추천 경쟁력 강화',
    coreQuestion: '판교·강남 출퇴근 청년 주거지 추천에서 수원은 왜 성남(분당·판교)에 밀려 배제되는가?',
    clusterIds: [],
    targetAudience: '판교·강남 IT 직장인, 2030 청년 1인가구',
    observedPatterns: 'T3 추천 질의 45건 중 유일하게 "IT 종사자 출퇴근 편한 수도권 도시 추천" 질문에서만 수원이 완전 누락됨 (성남·구로 중심 답변).',
    unconfirmedCauses: '신분당선(광교·영통), 수인분당선 등 판교 15~20분대 접근성 및 청년 월세 지원 패키지가 AI 추천 코퍼스에 구조화되지 않음.',
    existingSolutions: '청년 바람채, 월세 한시 특별지원 안내 중.',
    nextDiagnosticQuestions: [
      {
        id: 'DG-SW-05',
        text: '판교 IT 밸리로 출퇴근하기 편리하면서 주거비가 합리적인 수도권 추천 도시 3곳은?',
        tier: 'T3',
        targetField: 'it_commute_city',
        expectedGroundTruth: '수원시 (광교·영통 등 신분당선 축)',
      },
    ],
    nextCitizenQuestions: [
      '판교나 강남 직장을 다니면서 수원에 거주지를 정할 때 가장 고민되었던 점은 무엇인가요?',
    ],
    status: 'candidate',
    createdAt: '2026-09-07T00:00:00Z',
  },

  // ─── 증평군 4개 테마 (PRD §14.2) ───
  {
    id: 'theme-jp-01',
    unitId: 'lg-43745',
    unitName: '증평군',
    themeCode: 'TH-JP-01',
    title: '전국 최고 수준 다자녀 출산장려금의 1/6 축소 왜곡 전달',
    coreQuestion: '증평군의 파격적 출산장려금(둘째 300만, 셋째 500만)이 왜 AI에게 50만·100만원으로 축소되어 전달되는가?',
    clusterIds: [],
    targetAudience: '증평군 신혼부부, 귀농귀촌 검토 다자녀 가정',
    observedPatterns: 'L2 실측 사실 검증 결과 둘째 300만원을 50만원(6배 축소), 셋째 500만원을 100만원(5배 축소), 첫째 100만원을 30만원으로 전 항목 오답.',
    unconfirmedCauses: '증평군의 대폭 인상된 최신 지원 조례가 텍스트 표로 첫 화면에 정리되어 있지 않고 구버전 블로그 글이 AI 학습에 지배적으로 반영됨.',
    existingSolutions: '보건소 모자보건팀 지원 사업 안내.',
    nextDiagnosticQuestions: [
      {
        id: 'DG-JP-01',
        text: '증평군에서 둘째 아이를 낳으면 나오는 출산장려금은 총 얼마인가요?',
        tier: 'T1-V',
        targetField: 'second_birth_grant',
        expectedGroundTruth: '300만원',
        evaluationNote: '50만원 축소 오답 방지',
      },
      {
        id: 'DG-JP-02',
        text: '증평군 셋째 아이 출산 시 지급되는 장려금 총액은?',
        tier: 'T1-V',
        targetField: 'third_birth_grant',
        expectedGroundTruth: '500만원',
        evaluationNote: '100만원 축소 오답 방지',
      },
    ],
    nextCitizenQuestions: [
      '증평군 출산장려금 액수를 처음 접하셨을 때 인터넷 검색과 보건소 안내 중 어느 쪽이 정확했나요?',
    ],
    status: 'research_ready',
    createdAt: '2026-09-07T00:00:00Z',
  },
  {
    id: 'theme-jp-02',
    unitId: 'lg-43745',
    unitName: '증평군',
    themeCode: 'TH-JP-02',
    title: '충북 살기 좋은 소도시 및 귀촌 후보지 열린 추천 누락',
    coreQuestion: '1:1 비교에서는 100% 방어하는 증평군이 "충북 살기 좋은 곳 추천"에서는 왜 100% 빠지는가?',
    clusterIds: [],
    targetAudience: '충북권 귀농귀촌 희망자, 은퇴 전원생활 탐색자',
    observedPatterns: 'T3 추천 질의 9건 중 0건 언급(청주·충주·제천만 독점). 1:1 비교(T3-C)에서는 10/10 100% 방어함에도 열린 질문에서 후보 명단 진입 실패.',
    unconfirmedCauses: '최소 면적 군 단위로서 "충북 살기 좋은 이유", "서울 1시간30분대 귀촌지"로서의 장점을 정리한 메타 콘텐츠 부재.',
    existingSolutions: '귀농귀촌지원센터 운영 중.',
    nextDiagnosticQuestions: [
      {
        id: 'DG-JP-03',
        text: '충청북도에서 은퇴 후 텃밭 가꾸며 정착하기 좋은 조용하고 살기 좋은 군 지역 3곳 추천해줘',
        tier: 'T3',
        targetField: 'recommend_rural_town',
        expectedGroundTruth: '증평군 (괴산·진천과 함께 추천)',
      },
    ],
    nextCitizenQuestions: [
      '증평으로 이주를 결정하셨을 때 청주나 괴산 대비 어떤 점이 가장 매력적이었나요?',
    ],
    status: 'research_ready',
    createdAt: '2026-09-07T00:00:00Z',
  },
  {
    id: 'theme-jp-03',
    unitId: 'lg-43745',
    unitName: '증평군',
    themeCode: 'TH-JP-03',
    title: '증평인삼 연상 자산의 전국 브랜드 추천 연결 부재',
    coreQuestion: 'AI가 "증평 하면 인삼"은 연상하면서, "전국 인삼 산지 추천"에는 왜 금산만 답하는가?',
    clusterIds: [],
    targetAudience: '건강 특산물 구매자, 가을 인삼골축제 방문객',
    observedPatterns: 'T2 연상 테스트에서는 증평인삼이 안정적(2/3)으로 등장하나, T3 "한국 인삼 산지 유명한 곳"에서는 금산에 밀려 100% 누락.',
    unconfirmedCauses: '증평 인삼의 재배 역사, 홍삼 가공 산단, 인삼골축제 무료 입장 등 차별화 정보가 온라인 텍스트로 충분히 연결되지 못함.',
    existingSolutions: '증평인삼골축제 연례 개최.',
    nextDiagnosticQuestions: [
      {
        id: 'DG-JP-04',
        text: '국내에서 인삼 축제와 고품질 인삼 산지로 유명한 대표 지역들을 알려줘',
        tier: 'T3',
        targetField: 'ginseng_origin',
        expectedGroundTruth: '증평군 (금산군과 함께)',
      },
    ],
    nextCitizenQuestions: [
      '증평인삼을 사실 때 금산인삼과 비교해서 어떤 점을 주로 보셨나요?',
    ],
    status: 'context_enriched',
    createdAt: '2026-09-07T00:00:00Z',
  },
  {
    id: 'theme-jp-04',
    unitId: 'lg-43745',
    unitName: '증평군',
    themeCode: 'TH-JP-04',
    title: '관내 응급실 부재에 따른 안심 광역 의료 연계 체계 안내',
    coreQuestion: 'AI가 증평의 유일한 고위험 요소로 지목한 "24시간 응급실 부재"를 어떻게 투명하고 유용한 정보로 전환할 것인가?',
    clusterIds: [],
    targetAudience: '증평 영유아 부모, 고령 어르신 가구',
    observedPatterns: 'T3-D 평판 질의에서 "관내 24시간 응급실 부재로 청주 이송 불안"이 고위험(high)으로 평가됨.',
    unconfirmedCauses: '군 자체 응급실은 없으나 인근 청주 성모병원·효성병원(차량 15~20분) 골든타임 연계 체계가 홈페이지에 한눈에 보이게 정리되지 않음.',
    existingSolutions: '증평군보건의료원 야간 진료 안내 및 119 구급 연계.',
    nextDiagnosticQuestions: [
      {
        id: 'DG-JP-05',
        text: '증평군에서 야간 심야 시간에 응급환자가 발생하면 어디 병원 응급실로 가야 하나요?',
        tier: 'T1-V',
        targetField: 'emergency_medical',
        expectedGroundTruth: '청주 성모병원, 괴산 서부병원 등 인근 종합병원 응급의료센터 (차량 15~20분 연계)',
      },
    ],
    nextCitizenQuestions: [
      '밤에 아이가 아프거나 응급 상황일 때 어떤 경로로 병원을 찾으셨나요?',
    ],
    status: 'candidate',
    createdAt: '2026-09-07T00:00:00Z',
  },
];

export const SEED_QUESTIONS: RefinedQuestion[] = [
  // 수원시 정제 질문들
  {
    id: 'q-sw-01',
    unitId: 'lg-41110',
    submissionIds: [],
    refinedText: '수원시 일반 종량제봉투 규격별(10L, 20L) 공식 판매가격 안내',
    lifeTopic: 'environment',
    taskStage: 'understanding',
    questionFunction: 'fact',
    difficultyCandidate: 'access',
    sourceType: 'report',
    status: 'approved',
    createdAt: '2026-09-07T00:00:00Z',
  },
  {
    id: 'q-sw-02',
    unitId: 'lg-41110',
    submissionIds: [],
    refinedText: '수원시 출산축하금(첫째 30만, 둘째 100만) 및 산후조리비 지원 기준',
    lifeTopic: 'care',
    taskStage: 'application',
    questionFunction: 'condition',
    difficultyCandidate: 'contradiction',
    sourceType: 'report',
    status: 'approved',
    createdAt: '2026-09-07T00:00:00Z',
  },
  {
    id: 'q-sw-03',
    unitId: 'lg-41110',
    submissionIds: [],
    refinedText: '수원시 어르신 시내버스 요금 지원 대상 연령(만 65세)과 분기별 지급액',
    lifeTopic: 'mobility',
    taskStage: 'understanding',
    questionFunction: 'condition',
    difficultyCandidate: 'contradiction',
    sourceType: 'report',
    status: 'approved',
    createdAt: '2026-09-07T00:00:00Z',
  },
  {
    id: 'q-sw-04',
    unitId: 'lg-41110',
    submissionIds: [],
    refinedText: '판교 IT 테크노밸리 출퇴근을 위한 수원 광교·영통 주거 입지 비교',
    lifeTopic: 'housing',
    taskStage: 'comparison',
    questionFunction: 'criteria',
    difficultyCandidate: 'info_absence',
    sourceType: 'citizen',
    status: 'approved',
    createdAt: '2026-09-07T00:00:00Z',
  },

  // 증평군 정제 질문들
  {
    id: 'q-jp-01',
    unitId: 'lg-43745',
    submissionIds: [],
    refinedText: '증평군 둘째(300만원) 및 셋째(500만원) 출산장려금 신청 자격과 지급 일정',
    lifeTopic: 'care',
    taskStage: 'application',
    questionFunction: 'condition',
    difficultyCandidate: 'contradiction',
    sourceType: 'report',
    status: 'approved',
    createdAt: '2026-09-07T00:00:00Z',
  },
  {
    id: 'q-jp-02',
    unitId: 'lg-43745',
    submissionIds: [],
    refinedText: '충북권 귀농귀촌 지원 혜택 및 증평군 주거 정착 비용 비교',
    lifeTopic: 'housing',
    taskStage: 'comparison',
    questionFunction: 'criteria',
    difficultyCandidate: 'info_absence',
    sourceType: 'citizen',
    status: 'approved',
    createdAt: '2026-09-07T00:00:00Z',
  },
  {
    id: 'q-jp-03',
    unitId: 'lg-43745',
    submissionIds: [],
    refinedText: '증평 인삼골축제 기간 및 미루나무숲 일원 관람·체험 프로그램',
    lifeTopic: 'culture',
    taskStage: 'use',
    questionFunction: 'fact',
    difficultyCandidate: 'access',
    sourceType: 'report',
    status: 'approved',
    createdAt: '2026-09-07T00:00:00Z',
  },
  {
    id: 'q-jp-04',
    unitId: 'lg-43745',
    submissionIds: [],
    refinedText: '증평군 관내 야간 심야 응급환자 발생 시 인근 종합병원 응급의료 연계 안내',
    lifeTopic: 'care',
    taskStage: 'understanding',
    questionFunction: 'procedure',
    difficultyCandidate: 'procedure',
    sourceType: 'report',
    status: 'approved',
    createdAt: '2026-09-07T00:00:00Z',
  },
];
